/* This file was generated by SableCC (http://www.sablecc.org/). */

package dot.node;

import dot.analysis.*;

@SuppressWarnings("nls")
public final class AAssignment extends PAssignment
{
    private TId _left_;
    private TDirectedEdge _directedEdge_;
    private TId _right_;

    public AAssignment()
    {
        // Constructor
    }

    public AAssignment(
        @SuppressWarnings("hiding") TId _left_,
        @SuppressWarnings("hiding") TDirectedEdge _directedEdge_,
        @SuppressWarnings("hiding") TId _right_)
    {
        // Constructor
        setLeft(_left_);

        setDirectedEdge(_directedEdge_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AAssignment(
            cloneNode(this._left_),
            cloneNode(this._directedEdge_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignment(this);
    }

    public TId getLeft()
    {
        return this._left_;
    }

    public void setLeft(TId node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TDirectedEdge getDirectedEdge()
    {
        return this._directedEdge_;
    }

    public void setDirectedEdge(TDirectedEdge node)
    {
        if(this._directedEdge_ != null)
        {
            this._directedEdge_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._directedEdge_ = node;
    }

    public TId getRight()
    {
        return this._right_;
    }

    public void setRight(TId node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._directedEdge_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._directedEdge_ == child)
        {
            this._directedEdge_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((TId) newChild);
            return;
        }

        if(this._directedEdge_ == oldChild)
        {
            setDirectedEdge((TDirectedEdge) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
