/* This file was generated by SableCC (http://www.sablecc.org/). */

package dot.analysis;

import java.util.*;
import dot.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPCreateSingleNode().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inACreateSingleNode(ACreateSingleNode node)
    {
        defaultIn(node);
    }

    public void outACreateSingleNode(ACreateSingleNode node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACreateSingleNode(ACreateSingleNode node)
    {
        inACreateSingleNode(node);
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        outACreateSingleNode(node);
    }

    public void inACreatePcNodes(ACreatePcNodes node)
    {
        defaultIn(node);
    }

    public void outACreatePcNodes(ACreatePcNodes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACreatePcNodes(ACreatePcNodes node)
    {
        inACreatePcNodes(node);
        if(node.getParent() != null)
        {
            node.getParent().apply(this);
        }
        if(node.getChild() != null)
        {
            node.getChild().apply(this);
        }
        outACreatePcNodes(node);
    }
}
